-- SCOTT 계정으로 사용자 생성
CREATE USER ORCLSTUDY   --ID
IDENTIFIED BY ORACLE;   --PASSWORD
-- 오류! 데이터베이스 관리 권한을 가진 사용자만이 생성 가능
-- SYS, SYSTEM 계정으로 사용자 계정 생성

-- ORCLSTUDY 사용자에게 TEMP 테이블 권한 부여
CREATE TABLE TEMP(
    COL1    VARCHAR2(20),
    COL2    VARCHAR2(20)
);

GRANT SELECT ON TEMP TO ORCLSTUDY;
GRANT INSERT ON TEMP TO ORCLSTUDY;

SELECT * FROM TEMP;

--객체 권한 취소
REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;

--RESOURCE롤
--CREATE TRIGGER, CREATE SEQUENCE, CREATE TYPE, CREATE PROCEDURE,
--CREATE CLUSTER, CREATE OPERATOR, CREAT INDEXTYPE, CREATE TABLE

--15장 연습문제
--2.
GRANT SELECT ON EMP TO PREV_HW;
GRANT SELECT ON DEPT TO PREV_HW;
GRANT SELECT ON SALGRADE TO PREV_HW;

--3.
REVOKE SELECT ON SALGRADE FROM PREV_HW;