CREATE USER ORCLSTUDY   --ID
IDENTIFIED BY ORACLE;   --PASSWORD

--ORCLSTUDY 사용자에게 권한 부여하기
GRANT CREATE SESSION TO ORCLSTUDY;

-- 사용자 정보 조회
SELECT *
    FROM ALL_USERS
    WHERE USERNAME = 'ORCLSTUDY';
    
SELECT *
    FROM DBA_USERS
    WHERE USERNAME = 'ORCLSTUDY';
    
SELECT *
    FROM DBA_OBJECTS
    WHERE OWNER = 'ORCLSTUDY';
-- 객체(테이블 등)를 아직 생성하지 않았을 경우 검색 안됨

-- 사용자 정보(비밀번호) 변경
ALTER USER ORCLSTUDY
IDENTIFIED BY ORCL;

-- 사용자 정보 삭제
-- 삭제하려는 계정이 접속 상태이면 적용되지 않음
DROP USER ORCLSTUDY;

-- 사용자와 객체 모두를 삭제
DROP USER ORCLSTUDY CASCADE;


/*시스템 권한
CREATE USER / ALTER USER / DROP USER
CREATE SESSION / ALTER SESSION
CREATE TABLE / CREATE ANY TABLE / ALTER ANY TABLE / DROPT ANY TABLE


객체 권한
TABLE
- ALTER / DELETE / INDEX / INSERT / SELETE / UPDATE

VIEW
- DELETE / INSERT / SELETE / UPDATE
*/

-- 
CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

-- 사용자 권한 부여하기
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

-- 사용자 권한 취소하기
REVOKE RESOURCE, CREATE TABLE FROM ORCLSTUDY;

-- SYSTEM 계정으로 ROLESTUDY 롤 생성 및 권한 부여하기
CREATE ROLE ROLESTUDY;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;

GRANT ROLESTUDY TO ORCLSTUDY;

REVOKE ROLESTUDY FROM ORCLSTUDY;

-- 롤 삭제
DROP ROLE ROLESTUDY;

-- 15장 연습문제
--1.
CREATE USER PREV_HW
IDENTIFIED BY ORCL;

GRANT CREATE SESSION TO PREV_HW;
