CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;
    
SELECT *
FROM DEPT_TEMP;

--DEPT_TEMP 테이블에 데이터 추가하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
    VALUES(50,'DATABASE','SEOUL');
    
--INSERT 오류 발생
--1. 모자랄 경우
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
    VALUES(60, 'NETWORK');
--2. 많이 넣는 경우
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
    VALUES(60, 'NETWORK', 'BUSAN', 'WRONG');
--3. 데이터 형이 틀린 경우
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
    VALUES('WRONG', 'NETWORK', 'BUSAN');
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
    VALUES(600, 'NETWORK', 'BUSAN'); --NUMBER(2,0)

-- INSERT 문에 열 지정 없이 데이터 추가하기
INSERT INTO DEPT_TEMP
    VALUES(60,'NETWORK','BUSAN');
    
--NULL 을 지정하여 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
    VALUES(70,'WEB',NULL);

--빈 공백 문자열로 NULL 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
    VALUES(80,'MOBILE','');

--열 데이터를 넣지 않는 방식으로 NULL 데이터 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
    VALUES(90,'INCHEON');
    
--EMP_TEMP 테이블 생성 (구조만 가져오고 데이터는 가져오지 않음)
CREATE TABLE EMP_TEMP
    AS SELECT * 
            FROM EMP
            WHERE 1<>1;--거짓
    
-- INSERT문으로 날짜 데이터 입력하기(날짜 사이에 / 입력)
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(9999,'홍길동','PRESIDENT',NULL, '2001/01/01', 5000, 1000, 10);
    
-- INSERT문으로 날짜 데이터 입력하기(날짜 사이에 - 입력)
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(1111,'성춘향','MANAGER',9999, '2001-01-05', 4000, NULL, 20);
    
    
--TO_DATE함수를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(2111,'이순신','MANAGER',9999, TO_DATE('07/01/2001','DD/MM/YYYY'), 4000, NULL, 20);
    
--SYSDATE를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(3111,'심청이','MANAGER',9999, SYSDATE, 4000, NULL, 30);
    
    
    
--서브 쿼리로 여러 데이터 추가하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
        FROM EMP E, SALGRADE S
        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
            AND S.GRADE =1;
            
--DEPT 테이블을 복사해서 DEPT_TEMP2 테이블 생성
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;
    
-- DEPT_TEMP2 테이블 업데이트 하기
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL';
    
--ROLLBACK으로 테이블 내용을 이전 상태로 되돌리기
ROLLBACK;

--테이블 데이터 중 일부분만 수정하기
UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
        LOC ='SEOUL'
    WHERE DEPTNO = 40;
    
--서브 쿼리로 데이터 일부분 수정하기
UPDATE DEPT_TEMP2
    SET(DNAME,LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                        WHERE DEPTNO=40)
    WHERE DEPTNO =40;
    
    
UPDATE DEPT_TEMP2
    SET DNAME = (SELECT DNAME
                    FROM DEPT
                    WHERE DEPTNO=40),
        LOC = (SELECT LOC
                    FROM DEPT
                    WHERE DEPTNO =40)
    WHERE DEPTNO =40;


--UPDATE문의 WHERE절에 서브쿼리 사용
UPDATE DEPT_TEMP2
    SET LOC ='SEOUL'
    WHERE DEPTNO =(SELECT DEPTNO
                        FROM DEPT_TEMP2
                        WHERE DNAME='OPERATIONS');
                        
--DELETE 문
CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;
    
--WHERE 절을 사용하여 데이터 일부분만 삭제
DELETE FROM EMP_TEMP2
    WHERE JOB='MANAGER';
    
--WHERE절에 서브쿼리를 사용하여 데이터 일부분만 삭제
DELETE FROM EMP_TEMP2
    WHERE EMPNO IN(SELECT EMPNO
                    FROM EMP_TEMP2 E, SALGRADE S
                    WHERE SAL BETWEEN LOSAL AND HISAL
                        AND GRADE=3
                        AND DEPTNO=30);

--테이블에 있는 전체 데이터 삭제하기
DELETE FROM EMP_TEMP2;
                
                
--연습문제 10장
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;


--1.
INSERT INTO CHAP10HW_DEPT
    VALUES (50,'ORACLE','BUSAN');
INSERT INTO CHAP10HW_DEPT
    VALUES (60,'SQL','ILSAN');
INSERT INTO CHAP10HW_DEPT
    VALUES (70,'SELECT','INCHEON');
INSERT INTO CHAP10HW_DEPT
    VALUES (80,'DML','BUNDANG');
    
    
--2.
INSERT INTO CHAP10HW_EMP
    VALUES(7201,'TEST_USER1','MANAGER', 7788,'2016/01/02',4500,NULL,50);
INSERT INTO CHAP10HW_EMP
    VALUES(7202,'TEST_USER2','CLERK', 7201,'2016/02/21',1800,NULL,50);
INSERT INTO CHAP10HW_EMP
    VALUES(7203,'TEST_USER3','ANALYST', 7201,'2016/04/11',3400,NULL,60);
INSERT INTO CHAP10HW_EMP
    VALUES(7204,'TEST_USER4','SALESMAN', 7201,'2016/05/31',2700,300,60);
INSERT INTO CHAP10HW_EMP
    VALUES(7205,'TEST_USER5','CLERK', 7201,'2016/07/20',2600,NULL,70);
INSERT INTO CHAP10HW_EMP
    VALUES(7206,'TEST_USER6','CLERK', 7201,'2016/09/08',2600,NULL,70);
INSERT INTO CHAP10HW_EMP
    VALUES(7207,'TEST_USER7','LECTURER', 7201,'2016/10/28',2300,NULL,80);
INSERT INTO CHAP10HW_EMP
    VALUES(7208,'TEST_USER8','STUDENT', 7201,'2018/03/09',1200,NULL,80);
    
--3.
UPDATE CHAP10HW_EMP
    SET DEPTNO = 70
    WHERE SAL > (SELECT AVG(SAL)--1800
                    FROM CHAP10HW_EMP
                    GROUP BY DEPTNO
                    HAVING DEPTNO=50);
                    
SELECT *
FROM CHAP10HW_EMP
ORDER BY DEPTNO;

--해답
SELECT AVG(SAL)--1800
    FROM CHAP10HW_EMP
    WHERE DEPTNO=50;

--4.
UPDATE CHAP10HW_EMP
    SET SAL = SAL*1.1,
        DEPTNO=80
    WHERE HIREDATE > (SELECT MIN(HIREDATE)
                        FROM CHAP10HW_EMP
                        WHERE DEPTNO =60);
                        
SELECT *
FROM CHAP10HW_EMP
WHERE DEPTNO =60
ORDER BY HIREDATE;


--5.
DELETE FROM CHAP10HW_EMP
    WHERE EMPNO IN (SELECT EMPNO
                        FROM CHAP10HW_EMP E, SALGRADE S
                        WHERE SAL BETWEEN LOSAL AND HISAL
                            AND GRADE =5);
                            
SELECT *
    FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
    WHERE SAL BETWEEN LOSAL AND HISAL
    AND GRADE =5;