--EMP 테이블 데이터 개수 출력
SELECT COUNT(*)
FROM EMP;

--부서 번호가 30번인 직원의 수 구하기
SELECT COUNT(*)
    FROM EMP
    WHERE DEPTNO =30;
    
-- COUNT 함수를 이용해서 추가 수당 열 개수
SELECT COUNT(COMM),COUNT(*)
    FROM EMP;
    
--부서 번호가 10번인 사원들의 최대,최소,평균 급여 출력
SELECT MAX(SAL), MIN(SAL), ROUND(AVG(SAL),0)
FROM EMP
WHERE DEPTNO =10;

--부서별 급여 평균 출력
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

--GROUP BY절에 없는 열을 SELECT절에 포함했을 경우
SELECT ENAME,DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO,ENAME;

--GROUP BY 절과 HAVING 절을 사용하여 출력
SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL)>=2000
ORDER BY DEPTNO, JOB;

--
SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
WHERE AVG(SAL) >=2000
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB; --오류

--WHERE 절과 HAVING절 모두 사용한 경우
SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
WHERE SAL<=3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL)>=2000
ORDER BY DEPTNO, JOB;

--7장 연습문제
--1.
SELECT DEPTNO,
        TRUNC(AVG(SAL)) AS SVG_SAL,
        MAX(SAL) AS MAX_SAL,
        MIN(SAL) AS MIN_SAL,
        COUNT(*) AS CNT
    FROM EMP
    GROUP BY DEPTNO;
    
--2.
SELECT JOB, COUNT(*)
    FROM EMP
    GROUP BY JOB
    HAVING COUNT(*)>=3;
    
--3.
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIER_YEAR,
        DEPTNO,
        COUNT(*)
    FROM EMP
    GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO;

--4.
SELECT NVL2(COMM,'O','X') AS EXIST_COMM, COUNT(*)AS CNT
    FROM EMP
    GROUP BY NVL2(COMM,'O','X');
    
--5.
SELECT DEPTNO, 
        TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,
        COUNT(*) AS CNT,
        MAX(SAL) AS MAX_SAL,
        SUM(SAL) AS SUM_SAL,
        AVG(SAL) AS AVG_SAL
    FROM EMP
    GROUP BY DEPTNO, TO_CHAR(HIREDATE,'YYYY');