-- 7장 연습 문제
--1.
SELECT D.DEPTNO,DNAME, EMPNO, ENAME, SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND SAL>2000;
    
--NATURAL JOIN
SELECT DEPTNO,DNAME, EMPNO, ENAME, SAL
    FROM EMP E NATURAL JOIN DEPT D
    WHERE SAL>2000;
    
--2.
SELECT D.DEPTNO, DNAME, 
        TRUNC(AVG(SAL))AS AVG_SAL,
        MAX(SAL) AS MAX_SAL,
        MIN(SAL) AS MIN_SAL,
        COUNT(D.DEPTNO) AS CNT
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    GROUP BY D.DEPTNO, DNAME;
    
--JOIN USING
SELECT DEPTNO, DNAME, 
        TRUNC(AVG(SAL))AS AVG_SAL,
        MAX(SAL) AS MAX_SAL,
        MIN(SAL) AS MIN_SAL,
        COUNT(DEPTNO) AS CNT
    FROM EMP E JOIN DEPT D USING(DEPTNO)
    GROUP BY DEPTNO, DNAME;
    
--3.
SELECT D.DEPTNO, DNAME, EMPNO, ENAME, JOB, SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO(+) = D.DEPTNO
    ORDER BY D.DEPTNO, DNAME;
    
--RIGHT OUTER JOIN
SELECT D.DEPTNO, DNAME, EMPNO, ENAME, JOB, SAL
    FROM EMP E RIGHT OUTER JOIN DEPT D ON(E.DEPTNO=D.DEPTNO)
    ORDER BY D.DEPTNO, DNAME;
    
--4.
SELECT D.DEPTNO, D.DNAME,
        E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, E1.DEPTNO AS DEPTNO_1,
        S.LOSAL, S.HISAL, S.GRADE,
        E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2, DEPT D, SALGRADE S
    WHERE E1.MGR = E2.EMPNO(+)
        AND E1.DEPTNO(+) = D.DEPTNO
        AND E1.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
    ORDER BY D.DEPTNO, E1.EMPNO;
    
--
SELECT D.DEPTNO, D.DNAME,
        E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, E1.DEPTNO AS DEPTNO_1,
        S.LOSAL, S.HISAL, S.GRADE,
        E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
    FROM DEPT D LEFT OUTER JOIN EMP E1 ON (D.DEPTNO =E1.DEPTNO)
                LEFT OUTER JOIN SALGRADE S ON (E1.SAL BETWEEN S.LOSAL AND S.HISAL)
                LEFT OUTER JOIN EMP E2 ON(E1.MGR=E2.EMPNO)
    ORDER BY D.DEPTNO, E1.EMPNO;