--오라클 연습문제 2


--1.
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;


--2.
SELECT JOB, MAX(SAL)
FROM EMP
GROUP BY JOB;

--3.
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

--4.
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB;

--5.
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE COMM !=0
GROUP BY DEPTNO;

-- 해답
SELECT DEPTNO, COUNT(CASE WHEN COMM > 0 THEN 1 END) AS CNT_COMM
FROM EMP
GROUP BY DEPTNO;

--6.
SELECT TO_CHAR(HIREDATE,'YYYY')AS HIREYEAR, COUNT(*)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY');

--7.
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL)>=2000;

--8.
SELECT DEPTNO, AVG(SAL), ENAME
FROM EMP
WHERE SAL>=1000
GROUP BY DEPTNO,ENAME
HAVING AVG(SAL)>=2000;

--해답
SELECT DEPTNO, AVG(SAL)
FROM EMP
WHERE SAL>=1000
GROUP BY DEPTNO
HAVING AVG(SAL)>=2000;

----------------------------------------------------
--1.
SELECT EMPNO, ENAME, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND ENAME = 'SCOTT';

--2.
SELECT ENAME,SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL;

--3.
SELECT ENAME, DNAME, SAL, GRADE
FROM EMP E, SALGRADE S, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND SAL BETWEEN LOSAL AND HISAL;
    
--4.
SELECT E.ENAME || ' 의 매니저는 ' || M.ENAME || ' 입니다.' AS ENAME
    FROM EMP E, EMP M
    WHERE E.MGR = M.EMPNO;
    
--5.
SELECT ENAME, JOB, D.DEPTNO, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND D.DEPTNO = 30;
    
--6.
SELECT ENAME, COMM, DNAME, LOC
    FROM EMP E JOIN DEPT D USING(DEPTNO)
    WHERE COMM >0;

--7.
SELECT ENAME, JOB, DEPTNO, DNAME
    FROM EMP E JOIN DEPT D USING(DEPTNO)
    WHERE LOC = 'DALLAS';
    
--8.
SELECT ENAME, DNAME
    FROM EMP E JOIN DEPT D USING(DEPTNO)
    WHERE ENAME LIKE '%A%';